set_target_properties(${PROJECT_NAME}
    PROPERTIES
    LINK_FLAGS "-Wl,-ObjC"
    MACOSX_BUNDLE TRUE
    MACOSX_BUNDLE_INFO_PLIST "${CMAKE_CURRENT_LIST_DIR}/Info.plist"
    XCODE_ATTRIBUTE_PRODUCT_NAME "Yotta iOS"
    XCODE_ATTRIBUTE_COMBINE_HIDPI_IMAGES "NO"
    #XCODE_ATTRIBUTE_CODE_SIGN_ENTITLEMENTS "${CMAKE_CURRENT_LIST_DIR}/app.entitlements";
    #XCODE_ATTRIBUTE_ASSETCATALOG_COMPILER_APPICON_NAME "AppIcon"
    #XCODE_ATTRIBUTE_ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME "LaunchImage"
)

target_link_libraries(${PROJECT_NAME}
    "-framework UIKit"
)